/**
 * Keyword → category slug hints for PT-BR quick entry (longest match wins).
 */
export const CATEGORY_KEYWORD_RULES: { slug: string; keywords: string[] }[] = [
  { slug: "transport", keywords: ["uber", "99", "taxi", "táxi", "onibus", "ônibus", "metro", "combustível", "combustivel", "estacionamento"] },
  { slug: "pets", keywords: ["cachorro", "gato", "pet", "veterinário", "veterinario", "ração", "racao"] },
  {
    slug: "food",
    keywords: [
      "uber eats",
      "china in box",
      "coco bambu",
      "fogo de chão",
      "fogo de chao",
      "bob's",
      "steakhouse",
      "churrascaria",
      "hamburgueria",
      "lanchonete",
      "pastelaria",
      "sorveteria",
      "self service",
      "kilometro de pizza", 
      "supermercado",
      "restaurante",
      "alimentação",
      "alimentacao",
      "refeição",
      "refeicao",
      "delivery de comida",
      "pediu comida",
      "outback",
      "madero",
      "habib's",
      "habibs",
      "mcdonald",
      "subway",
      "ragazzo",
      "gendai",
      "spoleto",
      "vende aqui",
      "kfc",
      "applebee",
      "texas roadhouse",
      "pizzaria",
      "hambúrguer",
      "hamburguer",
      "hamburger",
      "pastel",
      "esfiha",
      "tapioca",
      "açaí",
      "acai",
      "sushi",
      "temaki",
      "yakisoba",
      "comida japonesa",
      "comida chinesa",
      "comida mexicana",
      "comida italiana",
      "padaria",
      "confeitaria",
      "doceria",
      "cafeteria",
      "café",
      "cafe",
      "padoca",
      "mercado",
      "atacadão",
      "atacadao",
      "carrefour",
      "pão de açúcar",
      "pao de acucar",
      "extra",
      "ifood",
      "rappi",
      "ze delivery",
      "zé delivery",
      "aiqfome",
      "glovo",
      "pede.ai",
      "ubereats",
      "uber-eats",
      "delivery",
      "lanche",
      "lanchinho",
      "almoco",
      "almoço",
      "jantar",
      "ceia",
      "café da manhã",
      "cafe da manha",
      "brunch",
      "marmita",
      "marmitex",
      "livup",
      "yopro",
      "whey",
      "iogurte",
      "sorvete",
      "picolé",
      "picolete",
      "creme de leite",
    ],
  },
  { slug: "utilities", keywords: ["luz", "água", "agua", "gás", "gas", "internet", "telefone", "energia"] },
  { slug: "health", keywords: ["farmácia", "farmacia", "médico", "medico", "plano", "dentista", "hospital"] },
  {
    slug: "personal-care",
    keywords: [
      "corte de cabelo",
      "cabeleireiro",
      "cabeleireira",
      "cabeleireiros",
      "salão de beleza",
      "salao de beleza",
      "salão",
      "salao",
      "progressiva",
      "tintura",
      "luzes",
      "cabelo",
      "escova",
      "trancista",
      "barbearia",
      "barbeiro",
      "sobrancelha",
      "sobrancelhas",
      "design de sobrancelha",
      "microblading",
      "henna",
      "unhas",
      "manicure",
      "pedicure",
      "alongamento de unhas",
      "alongamento",
      "esmalte",
      "nails",
      "depilação",
      "depilacao",
      "cera depilatória",
      "cera depilatoria",
    ],
  },
  {
    slug: "entertainment",
    keywords: [
      "lazer",
      "diversão",
      "diversao",
      "cinema",
      "netflix",
      "spotify",
      "jogo",
      "show",
      "streaming",
      "festa",
      "balada",
      "bar",
      "parque",
      "hobby",
      "videogame",
      "videogames",
    ],
  },
  { slug: "housing", keywords: ["aluguel", "condomínio", "condominio", "iptu"] },
  {
    slug: "apartamento",
    keywords: [
      "evolução de obra",
      "evolucao de obra",
      "evolução construtiva",
      "evolucao construtiva",
      "parcela de obra",
      "pagamento evolução",
      "pagamento evolucao",
      "reforma do apartamento",
      "reforma no apartamento",
      "reforma apartamento",
      "reformar apartamento",
      "obra do apartamento",
      "apartamento na planta",
      "minha casa minha vida",
      "financiamento da obra",
      "cota incorporação",
      "cota incorporacao",
      "incorporadora",
      "construtora",
      "material de obra",
      "empreiteiro",
      "pedreiro",
      "gesso e drywall",
      "projeto arquitetônico",
      "projeto arquitetonico",
      "apartamento",
      "obra",
    ],
  },
  {
    slug: "casa",
    keywords: [
      "mercado livre",
      "mercadolivre",
      "casas bahia",
      "ponto frio",
      "pontofrio",
      "magazine luiza",
      "magalu",
      "americanas",
      "submarino",
      "shopee",
      "kabum",
      "leroy merlin",
      "telhanorte",
      "madeira madeira",
      "tok stok",
      "tok&stok",
      "mobly",
      "electrolux",
      "brastemp",
      "consul",
      "eletrodoméstico",
      "eletrodomestico",
      "móveis",
      "moveis",
      "utilidades domésticas",
      "utilidades domesticas",
      "amazon",
      "amazon.com",
      "geladeira",
      "fogão",
      "fogao",
      "microondas",
      "purificador",
      "aspirador",
      "liquidificador",
    ],
  },
  {
    slug: "shopping",
    keywords: [
      "lojas de roupa",
      "loja de roupa",
      "maquiagem",
      "cosmético",
      "cosmetico",
      "cosméticos",
      "cosmeticos",
      "perfume",
      "hidratante",
      "sabonete",
      "creme",
      "magazine",
      "roupa",
      "roupas",
      "calçados",
      "calcados",
      "tênis",
      "tenis",
      "sapato",
      "brechó",
      "brecho",
      "boutique",
      "presente",
    ],
  },
  { slug: "education", keywords: ["curso", "faculdade", "escola", "livro"] },
];
